#!/bin/python

import os, sys, random

specialChars = [" ", ",", ":", ";", "'", "\"",  "(", ")", "[", "]", "{", "}", "<", ">"]
i = 1
while i < len(sys.argv):
    f = sys.argv[i]
    file = os.getcwd()+"/"+f
    if os.path.isfile(file) or os.path.isdir(file):
        for c in specialChars:
            f = f.replace(c, "\\"+c)
            
        if f.endswith("/"):
            f = f[:-1]

        if os.path.exists(f):
            tmpFile = "tmp_"+f+"_"+str(int(random.random()*100000))
            open(tmpFile, "x")

            if os.path.isfile(f):
                command = "gzip -k9 "+f
            else:
                if os.path.exists(f+".zip"):
                    os.remove(f+".zip")
                command = "zip -r9 "+f+".zip "+f
            print(command)
            os.system(command)
            
            if os.path.exists(tmpFile) and os.path.isfile(tmpFile):
                os.remove(tmpFile)
    else:
        print(sys.argv[i]+" not file")
    
    i += 1
