[colors.bright]
black = "#333333"
blue = "#55FFFF"
cyan = "#00AAAA"
green = "#55FF55"
magenta = "#FF55FF"
red = "#FF5555"
white = "#FFFFFF"
yellow = "#FFFF55"

[colors.normal]
black = "#000000"
blue = "#0000AA"
cyan = "#5555FF"
green = "#00AA00"
magenta = "#AA00AA"
red = "#AA0000"
white = "#c5c8c6"
yellow = "#FFAA00"

[colors.primary]
background = "#080808"
foreground = "#c5c8c6"

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[mouse.bindings]]
action = "Paste"
mouse = "Middle"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8

[window.padding]
x = 2
y = 2
